### ISSUE TITLE
same name with 2 separate imports?

### ISSUE THREAD

**Issue by xgpt** [dglaude/CircuitPython_udraw_Absolute_Mouse#1]
code.py doesn't seem to work?

I don't understand how to call mouse_abs

**Comment by dglaude** [comment]
I have written this some time ago, and I don't remember with what version of CircuitPython this was working.
From the readme, you apparently have to copy the file mouse_abs.py into the adafruit_hid folder (that is inside /lib/).
So that file would be next to `mouse.py` or `mouse.mpy` (depending if you take the Python source code or pre-compiled adafruit_hid.

Also, once you have to copied boot.py, you may want to reset or power cycle your board as the USB parameter are set when the board initiate the communication with the host.

To help troubleshoot this:
* Make sure you use either the stable 7.3.3 or latest 8.0 alpha/beta
* Update the libraries (maybe with circup or discotool calling circup)
* Make sure you powercycle with every file at the right location

If it is not working, tell me more: What board, What version of CP, What version of the library (freeze output from circup display that, What file is put where.

Regards

**Comment by xgpt** [comment]
So, because Neradoc was kind enough to assist me and did so by forking this code, I'd like to direct you to that code before attempting to amateurishly answer your questions and quite likely introduce confusion to the matter. https://github.com/Neradoc/CircuitPython_Absolute_Mouse/

In #CircuitPython-help on discord yesterday, that was significant discussion assisting me in this matter.

I was able to get a simple program running, but I wasn't able to get your code running, just Neradoc's.

But basically I'm trying to adapt your code for an accessibility project for someone to be able to utilize their computing devices with increased independence.

How would I use circup to meet your request for debugging information? I have never used circup, preferring to freeze versions/libraries in github folders so I have a known-same-working-state to develop with, as these devices once sent out into the wild often don't make their way back onto my workbench.

**Comment by xgpt** [comment]
I was using a circuitplayground express however, and I believe the baked-in adafruit_hid library might have been causing an issue, despite assurances to the contrary that that would not happen, I then switched to a seeduino xiao rp2040 board, and intend to ship this product on either a pi pico or an rp2040. I say product but it's not like I've ever charged anyone for these products.

**Comment by dglaude** [comment]
Sorry @xgpt I totally lost track (and forgot) about this.
So I did not see your message.

I only discovered last week the fork that Neradoc did.
Actually the library is now on the Community Bundle of CircuitPython, so it is easy to install with discotool or circup (together with adafruit_hid to make sure you have the right version).

So I am happy you found someone to help and a solution.

I'll close this for now.
