### ISSUE TITLE
using mouse_abs without UDraw for mouse simulation?

### ISSUE THREAD

**Issue by gree303** [dglaude/CircuitPython_udraw_Absolute_Mouse#2]
thanks for sharing this neat project.
I'm working on something similar but without any input device attached to it.
May I ask for some details on how to use the mouse_abs library with adafruit_hid together?

Thanks in advance @dglaude

**Comment by dglaude** [comment]
My project/repo has been forked and is now part of Circuit Python Community bundle that group together many useful library: https://github.com/Neradoc/CircuitPython_Absolute_Mouse

In there you have a simple test: https://github.com/Neradoc/CircuitPython_Absolute_Mouse/blob/main/examples/absolute_mouse_simpletest.py that has no input device and drive adafruit_hid to move the mouse around.

**Comment by gree303** [comment]
works - awesome!
ty

**Comment by gree303** [comment]
@dglaude do you know if there is such a library for Arduino, like the one you have created?
It's the last piece to my project; it's awesome that your code works; but I'd need to rewrite my entire codebase from Arduino to Python.

I understand it's non of your business; just wondering in case you know some alternative I'm very open to any suggestion(s). Thanks.

**Comment by dglaude** [comment]
I may have found Arduino equivalent, but since I did not acknowledge that, I likely did not use it.
I would say Teensy has C code for HID and maybe one is absolute mouse. USB Host is not super common. But you need code where you can fully describe the USB-HID descriptor to go for absolute mouse... that is where it become a unicorn that only a good search engine and checking 10-20 responses help you find.

**Comment by gree303** [comment]
Yeah - you are right; ... one of the better sites = [Teensy 3.1](https://www.codeproject.com/Articles/1001891/A-USB-HID-Keyboard-Mouse-Touchscreen-emulator-with)

Thanks for your input and sharing your code. -best
